### ISSUE TITLE
Prepare function not adding constant

### ISSUE THREAD

**Issue by ll01** [ssoudan/unit-root#3]
looking at the python and R versions of the ad fuller
https://stats.stackexchange.com/questions/131148/the-difference-between-the-three-augmented-dickey-fuller-test-none-drift-trend
https://www.statsmodels.org/dev/_modules/statsmodels/tsa/tsatools.html#add_trend  (specifically looking at the ` trendarr = np.vander(
        np.arange(1, nobs + 1, dtype=np.float64), trendorder + 1
    )` line )
the proper prepare test  output should look like 
[[ 6.  3.  2.  1.]
 [10.  4.  3.  1.]
 [15.  5.  4.  1.]
 [21.  6.  5.  1.]
 [28.  7.  6.  1.]
 [36.  8.  7.  1.]
 [45.  9.  8.  1.]]
 for a lag of 2 and a constant trend. However, the test doesn't have the 4th column, is this a bug or am I missing something?

**Comment by ssoudan** [comment]
This is indeed a bug. What is implemented is the 'no constant no trend'. 
Thanks for identifying it.

The 'constant no trend' has the column of 1 (for the constant). And the 'trend' adds columns that are powers of the (1:n_obs)-range up to the order of the trend.

Want to give a shot a making `prepare` more generic so it can accommodate these different variants?

**Comment by ll01** [comment]
i'll try after work tomorrow.
